# Config file
# Parsing is case insensitive. If a limited number of options 
# is available for a certain choice they are listed in comments on 
# the same line.

# input and output may also be specified from command line by passing
# the -i and -o flags repectively. E.g.
# pearls -i path/to/input/image -o path/to/output/image
# If an argument is passed from command line, this is preferred over 
# the contents of this file.

[io]
input = "images/landscape.jpg"
output = "images/landscape_out.jpg"

[params]
subsize = "4x4"
ncolors = "100"
circsize = "24x24"
weights = "1.0, 0.0"
filter = "sdev" 		# Options: none, sdev
exec = "parallelx4"		# Options: sequential, parallelx4, parallelx8
postproc = "none"		# Options: none, origsize

[visuals]
show = "none"			# Options: none, original, result, both
